### ISSUE TITLE
Switch to Apache 2.0 license

### ISSUE THREAD

**Issue by timuralp** [NVIDIA/docker-swift#52]
I propose switching to Apache 2.0 license from GPLv2 for less scrutiny in any corporate use cases, while maintaining the same permissiveness. Here is a blurb on compatibility (or lack thereof) between these licenses: https://www.apache.org/licenses/GPL-compatibility.html. The incompatibility requires an explicit agreement for the switch.

**Comment by timuralp** [comment]
@pbinkley, as the original author of the project, do you have any objections to the licensing change?

**Comment by gaul** [comment]
GPL was a curious choice given that this project is mostly config files with a few scripts.  You need to get permission from all the contributors to relicense the project or remove their contributions.  `git shortlog -s` says that there are 10 contributors.  You have my permission to relicense under either Apache or MIT licenses.  Good luck!

**Comment by timuralp** [comment]
@gaul good point!

@daniellawrence @diwu1989 @The-Alchemist @majewsky @shooding @thiagodasilva you've all made contributions to this project. Can I have your permission to change the license to Apache 2.0 license?

**Comment by daniellawrence** [comment]
LGTM

**Comment by pbinkley** [comment]
👍 You have my permission to relicense to Apache 2.0.

**Comment by majewsky** [comment]
You have my permission.-- Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 06.01.21, 01:56 schrieb Timur Alperovich <notifications@github.com>:

   
  @gaul good point! 
  @daniellawrence @diwu1989 @The-Alchemist @majewsky @shooding @thiagodasilva you've all made contributions to this project. Can I have your permission to change the license to Apache 2.0 license?

**Comment by timuralp** [comment]
@kahing sorry I forgot to tag you in the above request!

**Comment by kahing** [comment]
You have my permission to relicense under either Apache or MIT licenses.

**Comment by thiagodasilva** [comment]
permission granted

**Comment by timuralp** [comment]
There are 5 contributions that we didn't get an acknowledgement from. I believe they are minor. Commit summaries:
1. Wei-Chih "add missing git clone of swift3" eefe4b1168845d0d77c5ec4ee130640f572cfb66
2. Wei-Chih "avoid debian interactive warning" 1e9d8aa0548824bb96521ffe182f18459e1ccd1b
3. Di Wu "Bind to both ipv4 and ipv6" cd472cf8419ce57302116f7e97aaecf1258232f8
4. The Alchemist "fixed URL to Swift All-in-one deployment" 5f2cfe0047afaff5e2f09aca7d81dae6dc7406b2
5. The Alchemist "minor formatting fixes" 590d9a881b50b0726ee1e39782ab612fa82ab259

I proposed a PR to switch license and updated the copyright: https://github.com/swiftstack/docker-swift/pull/53. I believe we have consensus for this change. Please let me know if there are any objections.

**Comment by diwu1989** [comment]
this is fine, thanks

**Comment by The-Alchemist** [comment]
permission granted

**Comment by timuralp** [comment]
Thank you all! I received guidance that switching the license needs to be more formal than our agreement in this GitHub issue. At the same time, we (at NVIDIA) no longer have a need internally to pursue a different license. I'm going to close this issue for the time being.
